title: Tom Farrand
description: I am a Deep Learning Engineer interested in privacy.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

about: ./
words: ./another-page.html

github:
  profile: https://github.com/FarrandTom